debug: true
spring:
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    name: products
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-e0n8b2hn2et7b3kt.us.auth0.com/
        #   audiences: http://resourcesrvr.nolasco.systems

#/auth0:
#/  audience: http://resourcesrvr.nolasco.systems

logging:
  level:
    org:
      springframework:
        security: DEBUG
